name: A Test master on JDK 17

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17.0
        distribution: temurin
        cache: maven

    - name: Run basic tests
      run: mvn clean verify
